Use grep -v

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -109,13 +109,8 @@ runs:
             
             result=$(fhir validate)
             echo $result
-            if echo $result | grep -Eq "*"INVALID"*"; then
-              echo "INVALID matched"
-            fi
-            
-            echo $INPUT_EXPECTED_FAILS
-            if echo $INPUT_EXPECTED_FAILS | grep -w -q VALIDATION_CONFORMANCE_DOTNET; then
-              echo "VALIDATION_CONFORMANCE_DOTNET"
+            if echo $result | grep -Eq "*"INVALID"*" && echo $INPUT_EXPECTED_FAILS | grep -w -q -v VALIDATION_CONFORMANCE_DOTNET; then
+              exit 1
             fi
             
             fhir pop > /dev/null
