Check if .NET is installed

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -49,6 +49,19 @@ runs:
   
     # Firely.Terminal steps
     
+    - name: Check if .NET is installed
+      run: |
+        if $INPUT_DOTNET_VALIDATION_ENABLED; then
+          if ! command -v dotnet &> /dev/null
+          then
+              echo "dotnet could not be found. Please see actions/setup-dotnet to set it up before running this action."
+              exit
+          fi
+        fi
+      shell: bash
+      env:
+        INPUT_DOTNET_VALIDATION_ENABLED: ${{ inputs.DOTNET_VALIDATION_ENABLED }}
+        
     # Test Firely SDK version
     - name: Check .NET SDK Version
       run: |
