Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -224,7 +224,14 @@ runs:
               if [[ "$packageDownloadResponseCode" == 2* && -s "$packageFile" ]]; then
                 tar -xzf $packageFile
                 fhirCacheLocation=$(fhir cache location --path)
-                echo "fhirCacheLocation: $fhirCacheLocation"
+                extractedFolderForPackage="${packageFile%.tgz}"
+                mv "$extractedFolderForPackage" "$fhirCacheLocation"
+
+                if [[ ! -d "$fhirCacheLocation/$extractedFolderForPackage" ]]; then
+                  echo "Error: Failed to move $extractedFolderForPackage to $fhirCacheLocation"
+                  exit 1
+                fi
+                
               else
                 echo "Failed to download terminology package '$packageName' in version '$packageVersion'."
                 [[ -e "$packageFile" ]] && rm "$packageFile"
