Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -190,34 +190,45 @@ runs:
           ztsDependencies=$(jq -r '.["zts-dependencies"] | keys[]?' package.json)
           if [[ -n "$ztsDependencies" ]]; then
             packagesForZtsToken=$(echo "$ztsDependencies" | jq -R . | jq -s '{packages: .}')
-            echo "$packagesForZtsToken"
+          
+            ztsTokenResponse=$(curl -s -w "\n%{http_code}" \
+              -X POST https://terminologien.bfarm.de/api/generate-token \
+              -H "Content-Type: application/json" \
+              -d "$packagesForZtsToken")
 
-          ztsTokenResponse=$(curl -s -w "\n%{http_code}" \
-            -X POST https://terminologien.bfarm.de/api/generate-token \
-            -H "Content-Type: application/json" \
-            -d "$packagesForZtsToken")
+            ztsTokenResponseBody=$(echo "$ztsTokenResponse" | sed '$d')
+            ztsTokenResponseCode=$(echo "$ztsTokenResponse" | tail -n 1)
 
-          ztsTokenResponseBody=$(echo "$ztsTokenResponse" | sed '$d')
-          ztsTokenResponseCode=$(echo "$ztsTokenResponse" | tail -n 1)
+            if [[ "$ztsTokenResponseCode" == 2* ]]; then
+                ztsAccessToken=$(echo "$ztsTokenResponseBody" | jq -r '.token')
+                if [[ "$ztsAccessToken" != "null" ]]; then
+                  echo "Successfully retrieved a token for the ZTS to do download the terminology packgages. Response code: $ztsTokenResponseCode"
+                else
+                  echo "Failed to retrieve a token for the ZTS to download the terminology packages. No token found in response."
+                  exit 1
+                fi
+            else
+                echo "Failed to retrieve a token for the ZTS to download the terminology packages. Response code: $ztsTokenResponseCode"
+                echo "Response body: $ztsTokenResponseBody"
+                exit 1
+            fi
 
-          if [[ "$ztsTokenResponseCode" == 2* ]]; then
-              ztsAccessToken=$(echo "$ztsTokenResponseBody" | jq -r '.token')
-              if [[ "$ztsAccessToken" != "null" ]]; then
-                echo "Successfully retrieved a token for the ZTS to do download the terminology packgages. Response code: $ztsTokenResponseCode"
+            for packageName in "${ztsDependencies[@]}"; do
+              packageVersion="2025.0.0"
+              echo "Trying to install terminology package '$packageName' in version '$packageVersion' from ZTS registry"
+              
+              packageFile="${package_name}-${package_version}.tgz"
+              packageDownloadResponseCode=$(curl -H "Authorization: Bearer $ztsAccessToken" \
+                https://terminologien.bfarm.de/packages/$packageName/$packageVersion \
+                -s -o "$packageFile" -w "%{packageDownloadResponseCode}")
+              if [[ "$packageDownloadResponseCode" == 2* && -s "$packageFile" ]]; then
+                echo "Download successful: $packageFile"
               else
-                echo "Failed to retrieve a token for the ZTS to download the terminology packages. No token found in response."
+                echo "Failed to download terminology package '$package' in version '$packageVersion'."
+                [[ -e "$packageFile" ]] && rm "$packageFile"
                 exit 1
               fi
-          else
-              echo "Failed to retrieve a token for the ZTS to download the terminology packages. Response code: $ztsTokenResponseCode"
-              echo "Response body: $ztsTokenResponseBody"
-              exit 1
-          fi
-
-          for package in "${ztsDependencies[@]}"; do
-            echo "Trying to install '$package' from ZTS registry"
-            curl -H "Authorization: Bearer $ztsAccessToken" https://terminologien.bfarm.de/packages/package/2050.0.0 -s -o $package-2025.0.0.tgz
-          done
+            done
           
           fi
         fi
