WIP: Add support for SUMMARY mode (Java validator)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -154,6 +154,19 @@ runs:
           
     - name: Validate all conformance resources in scope of the repository
       run: |
+      
+        print_output_details () {
+          levels=($(echo "$1" | ggrep -P '(Error|Warning|Information)'| ggrep -oP '(?<=\s)[^\s]+(?=\s@)'))
+          locations=($(echo "$1" | ggrep -oP '(?<=@\s)[^:]*(?=\s)'))
+          messages=($(echo "$1" | ggrep -oP '(?<=\s:\s).*'))
+          for i in "${!levels[@]}"; do
+            echo "Level: ${levels[$i]}"
+            echo "Location: ${locations[$i]}"
+            echo "Message: ${messages[$i]}"
+            echo -e ""
+          done
+        }
+        
         if $INPUT_JAVA_VALIDATION_ENABLED; then
           echo "Starting validation using Java validator (Conformance resources) ..."
           IG_DEPENDENCIES=$(jq '.dependencies | to_entries | map("-ig " + .key + "#" + .value) | join(" ")' package.json)
@@ -175,36 +188,42 @@ runs:
               pathToValidatedResource=$(echo "$javaValidatorOutput" | grep -P '\-\-\s' || true)
               pathToValidatedResource=($(echo "$pathToValidatedResource" | grep -oP '(?<=--\s).+(?=\s--)' || true))
               
-              resourceBoundaries=$(echo "$javaValidatorOutput" | grep -b -oP '(?<!-)-{2}\s' || true)
-              resourceBoundaries=($(echo "$resourceBoundaries" | cut -d: -f1))
+              if [ ${#pathToValidatedResource[@]} -eq 0 ]; then # Single resource validation only, no section header with resource path will be printed by the Java validator
+                echo "----"
+                pathToValidatedResource=$(echo "$javaValidatorOutput" | ggrep -oP '(?<=Validate\s).+(?=\s[0-9][0-9]:[0-9][0-9].[0-9]{0,})')
+                echo "Path to valiated resource: ${pathToValidatedResource}"
+                echo "----"
+                print_output_details "$javaValidatorOutput"
+              else # We encountered a directory with more than a single resource in it, Java validator output will differ (each resource will be printed with its own section)  
+                resourceBoundaries=$(echo "$javaValidatorOutput" | grep -b -oP '(?<!-)-{2}\s' || true)
+                resourceBoundaries=($(echo "$resourceBoundaries" | cut -d: -f1))
               
-              for i in "${!resourceBoundaries[@]}"; do
-                echo "----"
-                echo "Path to valiated resource: ${pathToValidatedResource[$i]}"
-                echo "----"
-                if [[ ! -z "${resourceBoundaries[$i+1]:-}" ]]; then
-                  offsetDiff=$(expr ${resourceBoundaries[$i+1]} - ${resourceBoundaries[$i]})
-                  resourceOutput=$(echo "$javaValidatorOutput" | tail -c+${resourceBoundaries[$i]} | head -c+${offsetDiff})
-                else
-                  resourceOutput=$(echo "$javaValidatorOutput" | tail -c+${resourceBoundaries[$i]})
-                fi
-                
-                levels=($(echo "$resourceOutput" | grep -P '(Error|Warning|Information)'| grep -oP '(?<=\s)[^\s]+(?=\s@)'))
-                locations=($(echo "$resourceOutput" | grep -oP '(?<=@\s)[^:]*(?=\s)'))
-                messages=($(echo "$resourceOutput" | grep -oP '(?<=\s:\s).*'))
-                
-                for i in "${!levels[@]}"; do
-                  echo "Level: ${levels[$i]}"
-                  echo "Location: ${locations[$i]}"
-                  echo "Message: ${messages[$i]}"
-                  echo -e ""
+                for i in "${!resourceBoundaries[@]}"; do
+                  echo "----"
+                  echo "Path to valiated resource: ${pathToValidatedResource[$i]}"
+                  echo "----"
+                  if [[ ! -z "${resourceBoundaries[$i+1]:-}" ]]; then
+                    offsetDiff=$(expr ${resourceBoundaries[$i+1]} - ${resourceBoundaries[$i]})
+                    resourceOutput=$(echo "$javaValidatorOutput" | tail -c+${resourceBoundaries[$i]} | head -c+${offsetDiff})
+                  else
+                    resourceOutput=$(echo "$javaValidatorOutput" | tail -c+${resourceBoundaries[$i]})
+                  fi
+
+                  levels=($(echo "$resourceOutput" | grep -P '(Error|Warning|Information)'| grep -oP '(?<=\s)[^\s]+(?=\s@)'))
+                  locations=($(echo "$resourceOutput" | grep -oP '(?<=@\s)[^:]*(?=\s)'))
+                  messages=($(echo "$resourceOutput" | grep -oP '(?<=\s:\s).*'))
+
+                  for i in "${!levels[@]}"; do
+                    echo "Level: ${levels[$i]}"
+                    echo "Location: ${locations[$i]}"
+                    echo "Message: ${messages[$i]}"
+                    echo -e ""
+                  done
+
                 done
-                
-              done
-              
+              fi
               IFS=$SAVEIFS
             fi
-          
           done
         fi
         echo "Finished validation using Java validator (Conformance resources) ..."
